spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: xxx
    password: xxx
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual